002- major changes
thows error:
edmiidz@m1 LiveKit_And_Twilio % node server/index.js
node:internal/modules/cjs/loader:1148
  throw err;
  ^

Error: Cannot find module '@livekit/protocol-js'
Require stack:
- /Users/edmiidz/Projects/GitHub/LiveKit_And_Twilio/server/AudioBridge.js
- /Users/edmiidz/Projects/GitHub/LiveKit_And_Twilio/server/index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1145:15)
    at Module._load (node:internal/modules/cjs/loader:986:27)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/Users/edmiidz/Projects/GitHub/LiveKit_And_Twilio/server/AudioBridge.js:3:25)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12)
    at Module.require (node:internal/modules/cjs/loader:1233:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/edmiidz/Projects/GitHub/LiveKit_And_Twilio/server/AudioBridge.js',
    '/Users/edmiidz/Projects/GitHub/LiveKit_And_Twilio/server/index.js'
  ]
}

Node.js v20.13.0
edmiidz@m1 LiveKit_And_Twilio %